# Generated by Django 3.1.6 on 2021-07-19 20:32
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
        migrations.DeleteModel(
            name="ListUser",
        ),
    ]
