# Generated by Django 3.1.6 on 2021-07-12 22:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
